import path from "path";
import { installSkillFromSource } from "./skills.js";
import { addMCPServer } from "./mcp.js";
import { runMaintenanceTick } from "./maintenance.js";
import { mutate } from "../organism/evolution.js";
import { enableCapability } from "./capabilities.js";

export interface EvolveAction {
  type: "install_skill" | "add_mcp" | "mutate_web_limb" | "maintenance_tick" | "enable_capability";
  params: Record<string, any>;
  reason: string;
}

export interface EvolvePlan {
  goal: string;
  actions: EvolveAction[];
}

export interface EvolveExecutionResult {
  type: string;
  success: boolean;
  message: string;
}

function findRepoSource(goal: string): string | null {
  const patterns = [
    /(https?:\/\/[^\s'"]+)/i,
    /(git@[^\s'"]+\.git)/i,
    /(file:\/\/[^\s'"]+)/i,
    /([A-Za-z0-9._/-]+\.git)/,
  ];
  for (const pattern of patterns) {
    const match = goal.match(pattern);
    if (match && match[1]) return match[1];
  }
  return null;
}

export function planEvolution(goal: string): EvolvePlan {
  const normalized = goal.toLowerCase();
  const actions: EvolveAction[] = [];
  const repoSource = findRepoSource(goal);

  if (repoSource || normalized.includes("install skill")) {
    actions.push({
      type: "install_skill",
      params: {
        source: repoSource || "",
      },
      reason: "Goal references adding external capability via skill installation.",
    });
  }

  if (
    normalized.includes("mcp")
    && normalized.includes("filesystem")
  ) {
    actions.push({
      type: "add_mcp",
      params: {
        name: "filesystem",
        command: "npx",
        args: ["@modelcontextprotocol/server-filesystem", "/tmp"],
      },
      reason: "Goal references MCP filesystem capability.",
    });
  }

  if (
    normalized.includes("web interface")
    || normalized.includes("dashboard")
    || normalized.includes("web ui")
  ) {
    actions.push({
      type: "mutate_web_limb",
      params: {
        filePath: "system/web-limb-generated.ts",
      },
      reason: "Goal references generating or evolving a web interface.",
    });
  }

  if (
    normalized.includes("sleep")
    || normalized.includes("maintenance")
    || normalized.includes("compact")
  ) {
    actions.push({
      type: "maintenance_tick",
      params: {},
      reason: "Goal references maintenance/sleep/compaction behavior.",
    });
  }

  if (normalized.includes("claude") || normalized.includes("anthropic")) {
    actions.push({
      type: "enable_capability",
      params: {
        name: "chat.anthropic",
        provider: "anthropic",
        model: "claude-3-5-sonnet-20241022",
      },
      reason: "Goal references Claude/Anthropic chat capability.",
    });
  } else if (normalized.includes("openai") || normalized.includes("gpt")) {
    actions.push({
      type: "enable_capability",
      params: {
        name: "chat.openai",
        provider: "openai",
        model: "gpt-4o",
      },
      reason: "Goal references OpenAI/GPT chat capability.",
    });
  } else if (normalized.includes("ollama")) {
    actions.push({
      type: "enable_capability",
      params: {
        name: "chat.ollama",
        provider: "ollama",
        model: "llama3.2",
      },
      reason: "Goal references Ollama chat capability.",
    });
  }

  return { goal, actions };
}

function generatedWebLimbContent(goal: string): string {
  const safeTitle = goal.replace(/`/g, "").slice(0, 80);
  return [
    "export function renderGeneratedWebLimb(): string {",
    `  const title = ${JSON.stringify(safeTitle || "Hatchling Web Limb")};`,
    "  return `<!doctype html><html><head><meta charset=\"utf-8\" /><title>${title}</title></head><body><h1>${title}</h1><p>Generated by evolve planner.</p></body></html>`;",
    "}",
    "",
  ].join("\n");
}

export async function executeEvolutionPlan(
  rootDir: string,
  plan: EvolvePlan,
  options: { approveUntrusted?: boolean; skillSubdir?: string } = {},
): Promise<EvolveExecutionResult[]> {
  const results: EvolveExecutionResult[] = [];

  for (const action of plan.actions) {
    try {
      if (action.type === "install_skill") {
        const source = String(action.params.source || "").trim();
        if (!source) {
          results.push({
            type: action.type,
            success: false,
            message: "No skill source found in goal. Include a path or repo URL.",
          });
          continue;
        }
        const installedPath = await installSkillFromSource(
          rootDir,
          source,
          undefined,
          options.skillSubdir,
          { approveUntrusted: Boolean(options.approveUntrusted) },
        );
        results.push({
          type: action.type,
          success: true,
          message: `Installed skill at ${installedPath}`,
        });
      } else if (action.type === "add_mcp") {
        const added = await addMCPServer(
          rootDir,
          String(action.params.name),
          String(action.params.command),
          Array.isArray(action.params.args) ? action.params.args.map((arg: any) => String(arg)) : [],
        );
        results.push({
          type: action.type,
          success: true,
          message: `Added MCP server ${added.name}`,
        });
      } else if (action.type === "mutate_web_limb") {
        const filePath = String(action.params.filePath || "system/web-limb-generated.ts");
        const mutation = await mutate(rootDir, filePath, generatedWebLimbContent(plan.goal));
        results.push({
          type: action.type,
          success: mutation.success,
          message: mutation.message,
        });
      } else if (action.type === "maintenance_tick") {
        const report = await runMaintenanceTick(rootDir);
        results.push({
          type: action.type,
          success: true,
          message: `Maintenance complete (autoSleep=${report.autoSleepTriggered}, pruned=${report.telemetryPruned})`,
        });
      } else if (action.type === "enable_capability") {
        const state = await enableCapability(rootDir, String(action.params.name), {
          provider: action.params.provider ? String(action.params.provider) : undefined,
          model: action.params.model ? String(action.params.model) : undefined,
        });
        results.push({
          type: action.type,
          success: true,
          message: `Capability ${String(action.params.name)} ${state.enabled ? "enabled" : "disabled"}`,
        });
      }
    } catch (error: any) {
      results.push({
        type: action.type,
        success: false,
        message: String(error.message || error),
      });
    }
  }

  return results;
}
