import http from "http";
import { PathGuard } from "./pathGuard.js";
import { getVitals } from "./vitals.js";
import { getAgentName } from "./soul.js";

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export async function renderWebDashboard(rootDir: string): Promise<string> {
  PathGuard.setRoot(rootDir);
  const [name, vitals] = await Promise.all([getAgentName(rootDir), getVitals()]);
  const safeName = escapeHtml(name);
  const safeVitals = escapeHtml(vitals);

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${safeName} | Hatchling Dashboard</title>
    <style>
      :root { color-scheme: light; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; }
      body { margin: 0; min-height: 100vh; background: radial-gradient(circle at 20% 20%, #f1f7ff, #f6fff7 60%, #fffaf1); color: #1f2937; }
      .wrap { max-width: 980px; margin: 0 auto; padding: 2.5rem 1.25rem; }
      .card { background: rgba(255,255,255,0.9); border: 1px solid #dbe7f3; border-radius: 16px; box-shadow: 0 20px 45px rgba(20, 34, 56, 0.12); padding: 1.5rem; }
      h1 { margin: 0 0 0.5rem; font-size: 1.9rem; letter-spacing: -0.015em; }
      .muted { color: #4b5563; margin-bottom: 1.25rem; }
      pre { margin: 0; overflow: auto; background: #0b1220; color: #dbeafe; border-radius: 12px; padding: 1rem; font-size: 0.9rem; line-height: 1.35; }
      .footer { margin-top: 1rem; color: #6b7280; font-size: 0.85rem; }
    </style>
  </head>
  <body>
    <main class="wrap">
      <section class="card">
        <h1>${safeName} Dashboard</h1>
        <div class="muted">Organic status overview generated by Hatchling.</div>
        <pre>${safeVitals}</pre>
        <div class="footer">Refresh to update vitals.</div>
      </section>
    </main>
  </body>
</html>`;
}

export async function startWebDashboard(rootDir: string, port: number): Promise<http.Server> {
  const server = http.createServer(async (_req, res) => {
    try {
      const html = await renderWebDashboard(rootDir);
      res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      res.end(html);
    } catch (error: any) {
      res.writeHead(500, { "content-type": "text/plain; charset=utf-8" });
      res.end(`Web dashboard error: ${error?.message || String(error)}`);
    }
  });

  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(port, "127.0.0.1", () => resolve());
  });
  return server;
}
