import http from "http";
import fs from "fs/promises";
import { PathGuard } from "./pathGuard.js";
import { getVitals } from "./vitals.js";
import { getAgentName } from "./soul.js";
import { renderCreature, renderCreatureSvg } from "./creature.js";
import { loadGenome } from "./creature-genome.js";
import { checkHealth } from "./health.js";
import { execSync } from "child_process";
import { summarizeCreatureEvents } from "./creature-events.js";

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export async function renderWebDashboard(rootDir: string): Promise<string> {
  PathGuard.setRoot(rootDir);
  const [name, vitals] = await Promise.all([getAgentName(rootDir), getVitals()]);
  const creatureSvg = await renderCreatureSvgForDashboard(rootDir);
  const status = await renderCreatureStatusChips(rootDir);
  const safeName = escapeHtml(name);
  const safeVitals = escapeHtml(vitals);

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${safeName} | Hatchling Dashboard</title>
    <style>
      :root { color-scheme: light; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; }
      body { margin: 0; min-height: 100vh; background: radial-gradient(circle at 20% 20%, #f1f7ff, #f6fff7 60%, #fffaf1); color: #1f2937; }
      .wrap { max-width: 980px; margin: 0 auto; padding: 2.5rem 1.25rem; }
      .card { background: rgba(255,255,255,0.9); border: 1px solid #dbe7f3; border-radius: 16px; box-shadow: 0 20px 45px rgba(20, 34, 56, 0.12); padding: 1.5rem; }
      .layout { display: grid; gap: 1rem; grid-template-columns: 280px 1fr; align-items: start; }
      .pet { background: linear-gradient(180deg, #ffffff, #f5faf5); border: 1px solid #d8e7de; border-radius: 12px; padding: 0.5rem; }
      .chips { display: flex; flex-wrap: wrap; gap: 0.5rem; margin: 0.25rem 0 1rem; }
      .chip { background: #eef6ff; border: 1px solid #cde0ff; color: #1f3d68; border-radius: 999px; padding: 0.2rem 0.6rem; font-size: 0.78rem; font-weight: 600; }
      .chip.activity { animation: pulse-chip 1.8s ease-in-out infinite; }
      @keyframes pulse-chip { 0%, 100% { transform: scale(1); } 50% { transform: scale(1.04); } }
      h1 { margin: 0 0 0.5rem; font-size: 1.9rem; letter-spacing: -0.015em; }
      .muted { color: #4b5563; margin-bottom: 1.25rem; }
      pre { margin: 0; overflow: auto; background: #0b1220; color: #dbeafe; border-radius: 12px; padding: 1rem; font-size: 0.9rem; line-height: 1.35; }
      .footer { margin-top: 1rem; color: #6b7280; font-size: 0.85rem; }
      @media (max-width: 900px) { .layout { grid-template-columns: 1fr; } .pet { max-width: 320px; margin: 0 auto; } }
    </style>
  </head>
  <body>
    <main class="wrap">
      <section class="card">
        <h1>${safeName} Dashboard</h1>
        <div class="muted">Organic status overview generated by Hatchling.</div>
        <div class="chips">${status}</div>
        <div class="layout">
          <div class="pet">${creatureSvg}</div>
          <pre>${safeVitals}</pre>
        </div>
        <div class="footer">Refresh to update vitals.</div>
      </section>
    </main>
  </body>
</html>`;
}

async function readJsonOrDefault<T>(relativePath: string, fallback: T): Promise<T> {
  try {
    const fullPath = await PathGuard.validatePath(relativePath, "read");
    return JSON.parse(await fs.readFile(fullPath, "utf-8")) as T;
  } catch {
    return fallback;
  }
}

async function renderCreatureSvgForDashboard(rootDir: string): Promise<string> {
  const config = await readJsonOrDefault("brain/config.json", {
    name: "hatchling",
    createdAt: rootDir,
  });
  const mutationState = await readJsonOrDefault("brain/mutation_state.json", {
    totalMutations: 0,
    successfulMutations: 0,
    sleepCycles: 0,
  });
  const curiosity = await readJsonOrDefault("brain/curiosity_state.json", { adjustedCuriosity: 5 });
  const quotas = await readJsonOrDefault("brain/quotas.json", {
    tokens: { today: 0, maxPerDay: 100000 },
  });
  const heartbeat = await readJsonOrDefault("brain/heartbeat.json", { lowEnergy: false });
  const health = await checkHealth();
  const commitCount = parseInt(execSync("git rev-list --count HEAD", { cwd: rootDir, encoding: "utf-8" }).trim(), 10);
  const tokenUsagePercent = (quotas.tokens.today / quotas.tokens.maxPerDay) * 100;
  const energyLevel = tokenUsagePercent > 90 ? "Critical" : tokenUsagePercent > 70 ? "Low" : "High";
  const seed = `${config.name || "hatchling"}:${config.createdAt || rootDir}`;
  const genome = await loadGenome(rootDir, seed);
  const creature = renderCreature({
    seed,
    commitCount,
    sleepCycles: Number(mutationState.sleepCycles || 0),
    successfulMutations: Number(mutationState.successfulMutations || 0),
    totalMutations: Number(mutationState.totalMutations || 0),
    curiosity: Number(curiosity.adjustedCuriosity || 5),
    energyLevel,
    safeMode: Boolean(health.safeMode),
    lowEnergy: Boolean(heartbeat.lowEnergy),
    palette: genome.palette,
    body: genome.body,
    eyes: genome.eyes,
    accent: genome.accent,
  });
  return renderCreatureSvg(creature, {
    seed,
    commitCount,
    sleepCycles: Number(mutationState.sleepCycles || 0),
    successfulMutations: Number(mutationState.successfulMutations || 0),
    totalMutations: Number(mutationState.totalMutations || 0),
    curiosity: Number(curiosity.adjustedCuriosity || 5),
    energyLevel,
    safeMode: Boolean(health.safeMode),
    lowEnergy: Boolean(heartbeat.lowEnergy),
    palette: genome.palette,
    body: genome.body,
    eyes: genome.eyes,
    accent: genome.accent,
  });
}

async function renderCreatureStatusChips(rootDir: string): Promise<string> {
  const social = await readJsonOrDefault("brain/social_memory.json", {
    users: {},
  } as { users: Record<string, { relationshipStage?: string }> });
  const strategy = await readJsonOrDefault("brain/autonomy_strategy.json", {
    goals: [],
  } as { goals: Array<{ status?: string }> });
  const events = await summarizeCreatureEvents(rootDir);
  const trusted = Object.values(social.users || {}).filter((u) => String(u.relationshipStage || "") === "trusted").length;
  const familiar = Object.values(social.users || {}).filter((u) => String(u.relationshipStage || "") === "familiar").length;
  const pendingGoals = (strategy.goals || []).filter((goal) => String(goal.status || "") === "pending").length;
  const chips = [
    { text: `trusted bonds: ${trusted}`, activity: false },
    { text: `familiar bonds: ${familiar}`, activity: false },
    { text: `pending goals: ${pendingGoals}`, activity: false },
    { text: `creature events: ${events.total}`, activity: true },
    { text: `recent event: ${events.recentTypes.slice(-1)[0] || "none"}`, activity: true },
  ];
  return chips
    .map((value) => `<span class="chip${value.activity ? " activity" : ""}">${escapeHtml(value.text)}</span>`)
    .join("");
}

export async function startWebDashboard(rootDir: string, port: number): Promise<http.Server> {
  const server = http.createServer(async (_req, res) => {
    try {
      const html = await renderWebDashboard(rootDir);
      res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      res.end(html);
    } catch (error: any) {
      res.writeHead(500, { "content-type": "text/plain; charset=utf-8" });
      res.end(`Web dashboard error: ${error?.message || String(error)}`);
    }
  });

  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(port, "127.0.0.1", () => resolve());
  });
  return server;
}
